---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: python
    tag: "3.13"

inputs:
  - name: repo

outputs:
  - name: output-dir

run:
  path: bash
  args:
    - -c
    - |
      cd repo/ci/tasks
      python -m pip install --upgrade pip &> /dev/null
      pip install numpy &> /dev/null
      python hello-world.py
